lib/lintPkg.js

https://github.com/LevelOneProject/Docs/issues/283

fix: license should now say 'see license in license'

---

lib/circleci.js

fix circleci.js to test, build and push images for branches star ting with 'ci_'

fix: fix circleci.js

---

lib/circleci.js

lcov.info use absolute path from the ubuntu machine

Fix lcov.info path

---

lib/cmd/branches.js
lib/cmd/helpers.js
lib/cmd/hooks.js
lib/cmd/status.js
lib/cmd/update.js
lib/cmd/usedev.js

Async/await is removed to make scripts compatible with node v6 which is current LTS

Node v6 compatible

---

lib/cmd/versionsup.js
lib/ut.js

Script checking current versions in package.json by using npm outdated command and updating version if needed

add script for updating versions in package.json to latest

---

bin/ut-release.js
lib/circleci.js

fix: fix build for Cicle CI

---

lib/circleci.js

replace slash in branch name only

fix: replace slash in branch name only

---

bin/ut-release.js

fix error that gets thrown when publishing a module for the first time

fix: publishing a module for the first time

---

bin/ut-release.js

log error in ut-release catch block and make process to exit

fix: log error in catch and make process to exit

---

bin/ut-release.js

fix: conflicting versions logic

---

eslint/.eslintrc

Change default parser with babel-eslint parser

feat: change parser

---

package.json

fix: add ut-versionbump in bin

---

lib/setEnv.js

Аllow dashes in implementation name.
E.g. impl-dw-admin

fix: allow dashes in implementation name

---

README.md
bin/angular.js
bin/ut-release-lerna.js
lib/dependencies.json
lib/tokenizeBranch.js
lib/versionBump.js
lib/versionInc.js
package.json

feat: lerna

---

lib/lintMd.js

fix: ingnore internal changelogs

---

README.md
lib/dependencies.json

fix: allow immutable 4.0.0-rc

---

lib/dependencies.json

chore: update dependencies

---

bin/ut-release.js
lib/dependencies.json

chore: allow json-schema-to-markdown

---

lib/dependencies.json

chore: allow ut-function.cbc

---

bin/ut-release-lerna.js
bin/ut-release.js
lib/audit.js

fix: adit and .lint/result.json in ut-release-lerna

---

bin/ut-release.js

fix: pass arguments to npm run doc

---

bin/ut-license.js
bin/ut-preversion.js
bin/ut-release.js
lib/license.js
lib/lintPkg.js
package.json

put the following in package.json scripts:
```
{
"license": "ut-license"
}
```
in order to triger licensing flow

WIP: ut-license command

---

bin/ut-preversion.js
bin/ut-release.js
lib/versionBump.js

npm script `"license": "ut-license"`

fix: license
